# Generated by Django 5.0.2 on 2024-03-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_actors_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date'], 'verbose_name_plural': 'Movies'},
        ),
    ]
